# Generated by Django 5.1.4 on 2024-12-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
